### ISSUE TITLE
Doesn't play anything for me in python 3

### ISSUE THREAD

**Issue by curiouswala** [hadware/gstreamer-python-player#3]
```
  from gi.repository import Gst, Gtk, GLib
/home/hasan/PycharmProjects/audioplayer/backup/seek_test.py:1: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gst, Gtk, GLib
Traceback (most recent call last):
  File "/home/hasan/PycharmProjects/audioplayer/backup/seek_test.py", line 78, in update_slider
    raise GenericException("Couldn't fetch song duration")
__main__.GenericException: Couldn't fetch song duration
Traceback (most recent call last):
  File "/home/hasan/PycharmProjects/audioplayer/backup/seek_test.py", line 78, in update_slider
    raise GenericException("Couldn't fetch song duration")
__main__.GenericException: Couldn't fetch song duration
```

The only parts i edited was these
  ```
        Gst.init("")

        # setting up the playbin elements
        self.playbin = Gst.ElementFactory.make("playbin", "playbin")
        self.playbin.set_property("uri", "file:///1cut.mp3")

```

**Comment by curiouswala** [comment]
sorry, my bad.
Fixed it.
```
        uri = 'file://' + os.path.abspath('1cut.mp3')
        self.playbin.set_property("uri", uri)
```

**Comment by hadware** [comment]
Ah well, good (i have to admit I was about to tell you to double check the filepath but I didn't want to be condescendingly suspicious about this)
